### ISSUE TITLE
目前AR技术扩展到“大”的物理世界

### ISSUE THREAD

**Issue by littlecole** [Tusiji/ar-design-club#3]
从桌面AR扩展到物理世界的数字孪生和增强，相关技术扩展到GIS、3D点云扫描、BIM等。

不知作者对这块有何研究。

**Comment by Tusiji** [comment]
- 技术标准未定，工具链缺失，哪怕是头部大厂
- 项目产品很长一段时间都是苦活累活定制活儿
- GIS和BIM在国内应用属于上升阶段，现有很多基建数据的信息化程度不高，数据打通是难点
- 不确定微软和华为能给这个市场带来多少水花
